# This template generates multiple jobs based on input parameters

parameters:
  platforms: ['linux']
  python_versions: ['3.6']
  tf_versions: ['']
  onnx_versions: ['']
  onnx_opsets: ['']
  onnx_backends: {onnxruntime: ['0.3.0']}
  job: {}
  run_setup: 'True'

jobs:
- ${{ each platform in parameters.platforms }}:
  - job: ${{ parameters.job.name }}
    pool:
      ${{ if eq(platform, 'linux') }}:
        vmImage: 'ubuntu-16.04'
      ${{ if eq(platform, 'windows') }}:
        vmImage: 'vs2017-win2016'
      ${{ if eq(platform, 'mac') }}:
        vmImage: 'macOS-10.13'

    # Generate matrix
    strategy:
      matrix:
        ${{ each python_version in parameters.python_versions }}:
          ${{ each tf_version in parameters.tf_versions }}:
            ${{ each onnx_version in parameters.onnx_versions }}:
              ${{ each onnx_backend in parameters.onnx_backends }}:
                ${{ each onnx_backend_version in onnx_backend.value }}:
                  ${{ each onnx_opset in parameters.onnx_opsets }}:
                    ${{ if ne(onnx_opset, '') }}:
                      ${{ format('{0} python{1} tf{2} onnx{3} opset{4} {5}{6}', platform, python_version, tf_version, onnx_version, onnx_opset, onnx_backend.key, onnx_backend_version) }}:
                        CI_PYTHON_VERSION: '${{ python_version }}'
                        CI_TF_VERSION: '${{ tf_version }}'
                        CI_ONNX_VERSION: '${{ onnx_version }}'
                        CI_ONNX_OPSET: '${{ onnx_opset }}'
                        CI_ONNX_BACKEND: '${{ onnx_backend.key }}'
                        CI_ONNX_BACKEND_VERSION: '${{ onnx_backend_version }}'

                        ${{ if eq(tf_version, '') }}:
                          CI_PIP_TF_NAME: 'tensorflow'
                        ${{ if ne(tf_version, '') }}:
                          CI_PIP_TF_NAME: ${{ format('tensorflow=={0}', tf_version) }}

                        ${{ if eq(onnx_version, '') }}:
                          CI_PIP_ONNX_NAME: 'onnx'
                        ${{ if ne(onnx_version, '') }}:
                          CI_PIP_ONNX_NAME: ${{ format('onnx=={0}', onnx_version) }}

                        ${{ if eq(onnx_backend_version, '') }}:
                          CI_PIP_ONNX_BACKEND_NAME: '${{ onnx_backend.key }}'
                        ${{ if ne(onnx_backend_version, '') }}:
                          CI_PIP_ONNX_BACKEND_NAME: ${{ format('{0}=={1}', onnx_backend.key, onnx_backend_version) }}

                    ${{ if eq(onnx_opset, '') }}:
                      ${{ format('{0} python{1} tf{2} onnx{3} {4}{5}', platform, python_version, tf_version, onnx_version, onnx_backend.key, onnx_backend_version) }}:
                        CI_PYTHON_VERSION: '${{ python_version }}'
                        CI_TF_VERSION: '${{ tf_version }}'
                        CI_ONNX_VERSION: '${{ onnx_version }}'
                        CI_ONNX_BACKEND: '${{ onnx_backend.key }}'
                        CI_ONNX_BACKEND_VERSION: '${{ onnx_backend_version }}'

                        ${{ if eq(tf_version, '') }}:
                          CI_PIP_TF_NAME: 'tensorflow'
                        ${{ if ne(tf_version, '') }}:
                          CI_PIP_TF_NAME: ${{ format('tensorflow=={0}', tf_version) }}

                        ${{ if eq(onnx_version, '') }}:
                          CI_PIP_ONNX_NAME: 'onnx'
                        ${{ if ne(onnx_version, '') }}:
                          CI_PIP_ONNX_NAME: ${{ format('onnx=={0}', onnx_version) }}

                        ${{ if eq(onnx_backend_version, '') }}:
                          CI_PIP_ONNX_BACKEND_NAME: '${{ onnx_backend.key }}'
                        ${{ if ne(onnx_backend_version, '') }}:
                          CI_PIP_ONNX_BACKEND_NAME: ${{ format('{0}=={1}', onnx_backend.key, onnx_backend_version) }}

    # Insert all properties other than pool/steps/strategy
    ${{ each pair in parameters.job }}:
      ${{ if not(in(pair.key, 'pool', 'steps', 'strategy')) }}:
        ${{ pair.key }}: ${{ pair.value }}

    steps:
    - bash: env
      displayName: 'Display Environment Variables'

# TODO: ordinary python is preferred but built-in python3.6 does not have libpython3.6m.so, onnxruntime will fail with
# Error: 'libpython3.6m.so.1.0: cannot open shared object file: No such file or directory'
# so have to use conda here, may switch back to UsePythonVersion when the issue is fixed.
#    - task: UsePythonVersion@0
#      inputs:
#        versionSpec: '$(CI_PYTHON_VERSION)'
#        architecture: 'x64'

# TODO: Conda Environment task is deprecating, move to raw python after issue above is fixed.
# https://github.com/Microsoft/azure-pipelines-tasks/pull/9573
    - task: CondaEnvironment@1
      inputs:
        createCustomEnvironment: 'true'
        environmentName: 'tf2onnx'
        packageSpecs: 'python=$(CI_PYTHON_VERSION)'
        updateConda: 'false'

    - ${{ if eq(parameters.run_setup, 'True') }}:
      - template: 'setup.yml'

    # Insert original steps
    - ${{ parameters.job.steps }}
