# Test against latest onnxruntime nightly package

# TODO: change onnxruntime package name when nightly package is ready

jobs:
- template: 'templates/job_generator.yml'
  parameters:
    tf_versions: ['1.12']
    onnx_opsets: ['9']
    onnx_backends:
      onnxruntime: ['']
    job:
      displayName: 'unit_test'
      steps:
      - template: 'unit_test.yml'
