# Pylint

jobs:
- template: 'templates/job_generator.yml'
  parameters:
    job:
      steps:
      - bash: |
          set -ex
          pip install pylint
          pip freeze
          pylint --rcfile=tools/pylintrc --ignore=version.py --disable=cyclic-import tf2onnx tests/*.py tools
        displayName: 'Pylint'
