# Unit test, full matrix

jobs:
- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux', 'windows', 'mac']
    tf_versions: ['1.12', '1.11', '1.10', '1.9', '1.8', '1.7', '1.6', '1.5']
    onnx_opsets: ['9', '8', '7']
    onnx_backends:
      onnxruntime: ['0.3.0']
    job:
      steps:
      - template: 'unit_test.yml'
